export const DROPBOX_CLIENT_ID = process.env.NEXT_PUBLIC_DROPBOX_CLIENT_ID!; 
export const DROPBOX_REDIRECT_URL = process.env.NEXT_PUBLIC_DROPBOX_REDIRECT_URL!;
export const DROPBOX_CLIENT_SECRET = process.env.DROPBOX_CLIENT_SECRET!; 