export const DROPBOX_CLIENT_ID = process.env.NEXT_PUBLIC_DROPBOX_CLIENT_ID!; 
export const DROPBOX_REDIRECT_URL = process.env.NEXT_PUBLIC_DROPBOX_REDIRECT_URL!;
export const DROPBOX_CLIENT_SECRET = process.env.DROPBOX_CLIENT_SECRET!; 

export const ZOOM_CLIENT_ID = process.env.NEXT_PUBLIC_ZOOM_CLIENT_ID!; 
export const ZOOM_REDIRECT_URL = process.env.NEXT_PUBLIC_ZOOM_REDIRECT_URL!;
export const ZOOM_CLIENT_SECRET = process.env.ZOOM_CLIENT_SECRET!; 